### Creating a pointing system 
        - 2 point for the top 5 
        - 1 point for the top 10 
        - 0 point for the rest

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('player_info.csv')
df

,Player,Salary,Team,G,PTS,AST,TRB,STL,BLK,TOV,PF
0,Nikola Jokić,"$33,047,803",Denver Nuggets,55.0,24.6,10.0,11.7,1.3,0.7,3.6,2.6
1,Jaren Jackson Jr.,"$28,946,605",Memphis Grizzlies,44.0,16.7,0.8,6.6,1.1,3.3,1.5,3.4
2,De'Aaron Fox,"$30,351,780",Sacramento Kings,55.0,25.4,6.3,4.3,1.1,0.3,2.7,2.5
3,Kevin Durant,"$44,119,845",Phoenix Suns,1.0,23.0,2.0,6.0,0.0,2.0,2.0,0.0
4,Stephen Curry,"$48,070,014",Golden State Warriors,38.0,29.4,6.4,6.3,1.0,0.4,3.2,2.2
5,Luka Dončić,"$37,096,500",Dallas Mavericks,54.0,33.4,8.1,8.7,1.5,0.5,3.6,2.6
6,Rudy Gobert,"$38,172,414",Minnesota Timberwolves,52.0,13.4,0.9,11.5,0.8,1.3,1.8,3.0
7,Kawhi Leonard,"$42,492,492",Los Angeles Clippers,38.0,23.0,3.9,6.1,1.4,0.6,1.6,1.6
8,Russell Westbrook,"$47,063,478",Utah Jazz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CJ McCollum,"$33,333,333",New Orleans Pelicans,56.0,21.0,5.9,4.3,0.9,0.6,2.6,1.9
10,LeBron James,"$44,474,988",Los Angeles Lakers,47.0,29.5,6.9,8.4,0.9,0.6,3.1,1.7
11,Shai Gilgeous-Alexander,"$30,913,750",Oklahoma City Thunder,54.0,31.0,5.7,4.7,1.6,1.1,2.9,2.7
12,Damian Lillard,"$42,492,492",Portland Trail Blazers,49.0,32.3,7.1,4.4,0.9,0.3,3.2,1.9
13,Doug McDermott,"$13,750,000",San Antonio Spurs,55.0,9.8,1.4,2.1,0.2,0.1,0.9,1.8
14,John Wall,"$40,866,760",Houston Rockets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Giannis Antetokounmpo,"$42,492,492",Milwaukee Bucks,50.0,31.3,5.4,12.0,0.7,0.8,3.9,3.3
16,Jayson Tatum,"$30,351,780",Boston Celtics,59.0,30.3,4.7,8.7,1.0,0.8,3.0,2.1
17,Tobias Harris,"$37,633,050",Philadelphia 76ers,58.0,15.2,2.6,5.8,1.0,0.5,1.3,2.0
18,Donovan Mitchell,"$30,351,780",Cleveland Cavaliers,54.0,27.5,4.8,4.0,1.5,0.4,2.7,2.4
19,Jalen Brunson,"$27,733,332",New York Knicks,60.0,23.8,6.2,3.6,0.9,0.3,2.0,2.3
20,Ben Simmons,"$35,448,672",Brooklyn Nets,42.0,6.9,6.1,6.3,1.3,0.6,2.3,3.3
21,Jimmy Butler,"$37,653,300",Miami Heat,48.0,21.8,5.0,5.9,2.0,0.3,1.7,1.3
22,Trae Young,"$37,096,500",Atlanta Hawks,55.0,27.1,10.1,2.9,1.0,0.2,4.1,1.5
23,Pascal Siakam,"$35,448,672",Toronto Raptors,54.0,25.0,6.0,7.8,0.8,0.6,2.5,3.3
24,Bradley Beal,"$43,279,250",Washington Wizards,40.0,22.9,5.4,3.6,0.9,0.6,2.8,1.9
25,Zach LaVine,"$37,096,500",Chicago Bulls,59.0,24.3,3.9,4.7,0.9,0.2,2.6,2.2
26,Myles Turner,"$35,069,500",Indiana Pacers,54.0,18.1,1.4,7.9,0.6,2.3,1.7,3.4
27,Jonathan Isaac,"$17,400,000",Orlando Magic,11.0,5.0,0.5,4.0,1.3,0.4,0.4,0.5
28,Gordon Hayward,"$30,075,000",Charlotte Hornets,38.0,14.6,3.7,4.4,0.9,0.2,1.9,1.4
29,Bojan Bogdanović,"$19,550,000",Detroit Pistons,59.0,21.6,2.6,3.8,0.6,0.1,2.3,1.9

In [6]:
df = df.drop([3,8,14])
df

,Player,Salary,Team,G,PTS,AST,TRB,STL,BLK,TOV,PF
0,Nikola Jokić,"$33,047,803",Denver Nuggets,55.0,24.6,10.0,11.7,1.3,0.7,3.6,2.6
1,Jaren Jackson Jr.,"$28,946,605",Memphis Grizzlies,44.0,16.7,0.8,6.6,1.1,3.3,1.5,3.4
2,De'Aaron Fox,"$30,351,780",Sacramento Kings,55.0,25.4,6.3,4.3,1.1,0.3,2.7,2.5
4,Stephen Curry,"$48,070,014",Golden State Warriors,38.0,29.4,6.4,6.3,1.0,0.4,3.2,2.2
5,Luka Dončić,"$37,096,500",Dallas Mavericks,54.0,33.4,8.1,8.7,1.5,0.5,3.6,2.6
6,Rudy Gobert,"$38,172,414",Minnesota Timberwolves,52.0,13.4,0.9,11.5,0.8,1.3,1.8,3.0
7,Kawhi Leonard,"$42,492,492",Los Angeles Clippers,38.0,23.0,3.9,6.1,1.4,0.6,1.6,1.6
9,CJ McCollum,"$33,333,333",New Orleans Pelicans,56.0,21.0,5.9,4.3,0.9,0.6,2.6,1.9
10,LeBron James,"$44,474,988",Los Angeles Lakers,47.0,29.5,6.9,8.4,0.9,0.6,3.1,1.7
11,Shai Gilgeous-Alexander,"$30,913,750",Oklahoma City Thunder,54.0,31.0,5.7,4.7,1.6,1.1,2.9,2.7
12,Damian Lillard,"$42,492,492",Portland Trail Blazers,49.0,32.3,7.1,4.4,0.9,0.3,3.2,1.9
13,Doug McDermott,"$13,750,000",San Antonio Spurs,55.0,9.8,1.4,2.1,0.2,0.1,0.9,1.8
15,Giannis Antetokounmpo,"$42,492,492",Milwaukee Bucks,50.0,31.3,5.4,12.0,0.7,0.8,3.9,3.3
16,Jayson Tatum,"$30,351,780",Boston Celtics,59.0,30.3,4.7,8.7,1.0,0.8,3.0,2.1
17,Tobias Harris,"$37,633,050",Philadelphia 76ers,58.0,15.2,2.6,5.8,1.0,0.5,1.3,2.0
18,Donovan Mitchell,"$30,351,780",Cleveland Cavaliers,54.0,27.5,4.8,4.0,1.5,0.4,2.7,2.4
19,Jalen Brunson,"$27,733,332",New York Knicks,60.0,23.8,6.2,3.6,0.9,0.3,2.0,2.3
20,Ben Simmons,"$35,448,672",Brooklyn Nets,42.0,6.9,6.1,6.3,1.3,0.6,2.3,3.3
21,Jimmy Butler,"$37,653,300",Miami Heat,48.0,21.8,5.0,5.9,2.0,0.3,1.7,1.3
22,Trae Young,"$37,096,500",Atlanta Hawks,55.0,27.1,10.1,2.9,1.0,0.2,4.1,1.5
23,Pascal Siakam,"$35,448,672",Toronto Raptors,54.0,25.0,6.0,7.8,0.8,0.6,2.5,3.3
24,Bradley Beal,"$43,279,250",Washington Wizards,40.0,22.9,5.4,3.6,0.9,0.6,2.8,1.9
25,Zach LaVine,"$37,096,500",Chicago Bulls,59.0,24.3,3.9,4.7,0.9,0.2,2.6,2.2
26,Myles Turner,"$35,069,500",Indiana Pacers,54.0,18.1,1.4,7.9,0.6,2.3,1.7,3.4
27,Jonathan Isaac,"$17,400,000",Orlando Magic,11.0,5.0,0.5,4.0,1.3,0.4,0.4,0.5
28,Gordon Hayward,"$30,075,000",Charlotte Hornets,38.0,14.6,3.7,4.4,0.9,0.2,1.9,1.4
29,Bojan Bogdanović,"$19,550,000",Detroit Pistons,59.0,21.6,2.6,3.8,0.6,0.1,2.3,1.9

In [8]:
df = df.reset_index(drop=True)

In [30]:
df['Point'] = 0
df_copy = df.copy()

In [31]:
df["Point"] += df.G.apply(lambda x: 2 if x>55 else 1 if x>=50 else 0)
df["Point"] += df.PTS.apply(lambda x: 2 if x>30 else 1 if x>=25 else 0)
df["Point"] += df.AST.apply(lambda x: 2 if x>6.8 else 1 if x>=5 else 0)
df["Point"] += df.TRB.apply(lambda x: 2 if x>10 else 1 if x>=7 else 0)
df["Point"] += df.STL.apply(lambda x: 2 if x>1.3 else 1 if x>=1 else 0)
df["Point"] += df.BLK.apply(lambda x: 2 if x>1 else 1 if x>=0.6 else 0)
df["Point"] += df.TOV.apply(lambda x: -2 if x>3.2 else -1 if x>=2.7 else 0)
df["Point"] += df.PF.apply(lambda x: -2 if x>3 else -1 if x>=2.2 else 0)

In [33]:
new_df = df.sort_values('Point', ascending=False)
new_df = new_df.reset_index(drop=True)

In [36]:
new_df = new_df[['Player', 'Team','Salary', 'Point']]

In [40]:
new_df.sort_values('Salary', ascending=False)

                     Player                    Team       Salary  Point
24            Stephen Curry   Golden State Warriors  $48,070,014      1
4              LeBron James      Los Angeles Lakers  $44,474,988      4
22             Bradley Beal      Washington Wizards  $43,279,250      1
7             Kawhi Leonard    Los Angeles Clippers  $42,492,492      3
11    Giannis Antetokounmpo         Milwaukee Bucks  $42,492,492      3
9            Damian Lillard  Portland Trail Blazers  $42,492,492      3
6               Rudy Gobert  Minnesota Timberwolves  $38,172,414      4
12             Jimmy Butler              Miami Heat  $37,653,300      3
13            Tobias Harris      Philadelphia 76ers  $37,633,050      3
10               Trae Young           Atlanta Hawks  $37,096,500      3
2               Luka Dončić        Dallas Mavericks  $37,096,500      5
23              Zach LaVine           Chicago Bulls  $37,096,500      1
8             Pascal Siakam         Toronto Raptors  $35,448,672      3
19              Ben Simmons           Brooklyn Nets  $35,448,672      1
14             Myles Turner          Indiana Pacers  $35,069,500      2
3               CJ McCollum    New Orleans Pelicans  $33,333,333      4
5              Nikola Jokić          Denver Nuggets  $33,047,803      4
1   Shai Gilgeous-Alexander   Oklahoma City Thunder  $30,913,750      6
0              Jayson Tatum          Boston Celtics  $30,351,780      6
17             De'Aaron Fox        Sacramento Kings  $30,351,780      2
16         Donovan Mitchell     Cleveland Cavaliers  $30,351,780      2
26           Gordon Hayward       Charlotte Hornets  $30,075,000      0
20        Jaren Jackson Jr.       Memphis Grizzlies  $28,946,605      1
15            Jalen Brunson         New York Knicks  $27,733,332      2
18         Bojan Bogdanović         Detroit Pistons  $19,550,000      2
25           Jonathan Isaac           Orlando Magic  $17,400,000      1
21           Doug McDermott       San Antonio Spurs  $13,750,000      1